# This file can be used to setup a Dgraph cluster with 3 Dgraph servers and 1 Zero node on a
# Docker Swarm with replication.
# It expects three virtual machines with hostnames host1, host2 and host3 to be part of the swarm.
# There is a constraint to make sure that Dgraph servers run on a particular host.

# Data would be persisted to a docker volume called data-volume on the virtual machines which are
# part of the swarm.
# Run `docker stack deploy -c docker-compose-multi.yml` on the Swarm leader to start the cluster.

version: "3"
networks:
  dgraph:
services:
  zero:
    image: dgraph/dgraph:test
    volumes:
      - data-volume:/dgraph
    ports:
      - 6080:6080
    networks:
      - dgraph
    deploy:
      placement:
        constraints:
          - node.hostname == host1
    command: dgraph zero --port_offset -2000 --my=zero:5080 --replicas 3
  server_1:
    image: dgraph/dgraph:test
    hostname: "server_1"
    volumes:
      - data-volume:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    networks:
      - dgraph
    deploy:
      placement:
        constraints:
          - node.hostname == host1
    command: dgraph server --my=server_1:7080 --memory_mb=2048 --zero=zero:5080
  server_2:
    image: dgraph/dgraph:test
    hostname: "server_2"
    volumes:
      - data-volume:/dgraph
    ports:
      - 8081:8081
      - 9081:9081
    networks:
      - dgraph
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == host2
    command: dgraph server --my=server_2:7081 --memory_mb=2048 --zero=zero:5080 -o 1
  server_3:
    image: dgraph/dgraph:test
    hostname: "server_3"
    volumes:
      - data-volume:/dgraph
    ports:
      - 8082:8082
      - 9082:9082
    networks:
      - dgraph
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == host3
    command: dgraph server --my=server_3:7082 --memory_mb=2048 --zero=zero:5080 -o 2
volumes:
  data-volume:
